# Generated by Django 3.0.14 on 2022-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mom_classification', models.CharField(choices=[('XXXXX', 'Known Wizard  Killer'), ('XXXX', 'Dangerous'), ('XXX', 'Competent wizard should cope'), ('XX', 'Harmless'), ('X', 'Boring')], max_length=5)),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
