# Generated by Django 3.0.14 on 2022-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beast',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
