# Generated by Django 3.0.14 on 2022-03-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beasts', '0002_auto_20220316_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='beast',
            name='mom_classification',
        ),
        migrations.RemoveField(
            model_name='beast',
            name='name',
        ),
    ]
